name: Emacs Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Emacs
        run: sudo apt-get install emacs

      - name: Run tests
        run: emacs --batch -l ert -l tzc-tests.el -f ert-run-tests-batch-and-exit
